import React from "react";
import Layout from "../../components/Layout";
import ProjectPage from "../../components/ProjectPage";

const EndlessPoem = () => (
  <Layout>
    <ProjectPage
      title="Endless (Authorless) Poem"
      info="Algorithms | 2024"
      description={[
        "An endless poem generated by a simple Markov chain-based algorithm that constructs 4-gram probability distributions scraped from Tumblr's #word-vomit tag, four posts at a time.",
        "Titled as an Authorless poem, this project questions the authorship of the data used to train text large language models.",
        "Credits (posts from): @fizzwizz-22, @wyzechyld, @starry-eyer, @theogonize.",
      ]}
      media={[
        {
          type: "embed",
          embedCode: `<iframe title="vimeo-player" src="https://player.vimeo.com/video/1081535254?h=f32784ca2f" width="640" height="360" frameborder="0"    allowfullscreen></iframe>`,
        },
      ]}
    />
  </Layout>
);

export default EndlessPoem;
